## Loan Prediction problem

we are trying to predict whether a person will repay the loan amount or not based on multiple parameters.


In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [2]:
df = pd.read_csv('train_clean_data.csv',index_col=0)
df.head()

Loan_ID Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
1  LP001003          1             4583             1508.0       128.0   
2  LP001005          0             3000                0.0        66.0   
3  LP001006          0             2583             2358.0       120.0   
4  LP001008          0             6000                0.0       141.0   
5  LP001011          2             5417             4196.0       267.0   

   Loan_Amount_Term  Credit_History  gender_Male  married_Yes  \
1             360.0             1.0            1            1   
2             360.0             1.0            1            1   
3             360.0             1.0            1            1   
4             360.0             1.0            1            0   
5             360.0             1.0            1            1   

   education_Not Graduate  property_area_Semiurban  property_area_Urban  \
1                       0                        0                    0   
2                       0                        0                    1   
3                       1                        0                    1   
4                       0                        0                    1   
5                       0                        0                    1   

   self_employed_Yes  Loan_status_Y  
1                  0              0  
2                  1              1  
3                  0              1  
4                  0              1  
5                  1              1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 517 entries, 1 to 613
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Loan_ID                  517 non-null    object 
 1   Dependents               517 non-null    object 
 2   ApplicantIncome          517 non-null    int64  
 3   CoapplicantIncome        517 non-null    float64
 4   LoanAmount               517 non-null    float64
 5   Loan_Amount_Term         517 non-null    float64
 6   Credit_History           517 non-null    float64
 7   gender_Male              517 non-null    int64  
 8   married_Yes              517 non-null    int64  
 9   education_Not Graduate   517 non-null    int64  
 10  property_area_Semiurban  517 non-null    int64  
 11  property_area_Urban      517 non-null    int64  
 12  self_employed_Yes        517 non-null    int64  
 13  Loan_status_Y            517 non-null    int64  
dtypes: float64(4), int64(8), object

## Train test Split

In [4]:
X = df.drop(['Loan_ID','Dependents','Loan_status_Y'],axis =1 )
y = df['Loan_status_Y']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Averaging the results

In [5]:
model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3 = LogisticRegression()

In [6]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

LogisticRegression()

In [7]:
pred1 = model1.predict_proba(X_test)
pred2 = model2.predict_proba(X_test)
pred3 = model3.predict_proba(X_test)

In [8]:
pred3

array([[0.22413791, 0.77586209],
       [0.42565588, 0.57434412],
       [0.10644953, 0.89355047],
       [0.11740297, 0.88259703],
       [0.29444045, 0.70555955],
       [0.17866096, 0.82133904],
       [0.21909839, 0.78090161],
       [0.30012791, 0.69987209],
       [0.33675061, 0.66324939],
       [0.13888441, 0.86111559],
       [0.37765914, 0.62234086],
       [0.21574377, 0.78425623],
       [0.3416085 , 0.6583915 ],
       [0.18203131, 0.81796869],
       [0.22135497, 0.77864503],
       [0.2447911 , 0.7552089 ],
       [0.06481141, 0.93518859],
       [0.13467296, 0.86532704],
       [0.79532965, 0.20467035],
       [0.27542913, 0.72457087],
       [0.12391776, 0.87608224],
       [0.28826814, 0.71173186],
       [0.14427123, 0.85572877],
       [0.83975855, 0.16024145],
       [0.31948546, 0.68051454],
       [0.23408414, 0.76591586],
       [0.32861996, 0.67138004],
       [0.25291608, 0.74708392],
       [0.95907768, 0.04092232],
       [0.23574534, 0.76425466],
       [0.

In [9]:
final_pred = (pred1 + pred2 + pred3)/3

In [12]:
final_pred

array([[0.20324912, 0.79675088],
       [0.21140093, 0.78859907],
       [0.0358135 , 0.9641865 ],
       [0.17296424, 0.82703576],
       [0.56237827, 0.43762173],
       [0.12193307, 0.87806693],
       [0.13439945, 0.86560055],
       [0.11087598, 0.88912402],
       [0.1211193 , 0.8788807 ],
       [0.24650328, 0.75349672],
       [0.6695299 , 0.3304701 ],
       [0.40143003, 0.59856997],
       [0.2472452 , 0.7527548 ],
       [0.06712138, 0.93287862],
       [0.26971252, 0.73028748],
       [0.14863042, 0.85136958],
       [0.10072791, 0.89927209],
       [0.17857883, 0.82142117],
       [0.85757179, 0.14242821],
       [0.15852145, 0.84147855],
       [0.17470386, 0.82529614],
       [0.63340655, 0.36659345],
       [0.18760939, 0.81239061],
       [0.40516397, 0.59483603],
       [0.10843359, 0.89156641],
       [0.67362833, 0.32637167],
       [0.2300779 , 0.7699221 ],
       [0.21256965, 0.78743035],
       [0.44753579, 0.55246421],
       [0.47419506, 0.52580494],
       [0.

## Voting Classifier

We are taking the outputs of multiple classifiers like:
    1. Logistic Regression
    2. Random Forest 
    3. Gausian Naive Bayes
   
Then take the majority votes to decide the final classification.

In [10]:
clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = GaussianNB()

In [11]:
eclf1 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)],weights=[1,2,4],voting='soft')
eclf1 = eclf1.fit(X_train, y_train)
prediction = eclf1.predict(X_test)


from sklearn.metrics import classification_report , confusion_matrix

print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

           0       0.81      0.41      0.55        41
           1       0.84      0.97      0.90       130

    accuracy                           0.84       171
   macro avg       0.82      0.69      0.72       171
weighted avg       0.83      0.84      0.82       171

[[ 17  24]
 [  4 126]]


In [12]:
eclf2 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='soft')
eclf2 = eclf2.fit(X_train, y_train)
predict = eclf2.predict(X_test)
print(classification_report(y_test, predict))
print('\n')
print(confusion_matrix(y_test, predict))

              precision    recall  f1-score   support

           0       0.86      0.44      0.58        41
           1       0.85      0.98      0.91       130

    accuracy                           0.85       171
   macro avg       0.85      0.71      0.74       171
weighted avg       0.85      0.85      0.83       171



[[ 18  23]
 [  3 127]]
