In [1]:
import numpy as np

In [ ]:
pip install numpy

In [2]:
np.__version__

'1.26.4'

In [3]:
#1-D Array
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
#2-D Array
'''An array that has 1-D arrays as its elements is called a 2-D array.'''
array2=np.array([[1,2,3.3]
                ,[4,5,6.5]])
array2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
#3-D Array
'''An array that has 2-D arrays (matrices) as its elements is called 3-D array.'''
array3=np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
array4=np.array((12,13,14))
array4

array([12, 13, 14])

In [8]:
print(array1.ndim)

1


In [9]:
print(array2.ndim)

2


In [10]:
print(array3.ndim)

3


In [11]:
print(array4.ndim)

1


In [12]:
array5=np.array([1,2,3,5],ndmin=4)
array5

array([[[[1, 2, 3, 5]]]])

In [13]:
print(array5.ndim)

4


In [14]:
array2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
array2[0][1]

2.0

In [23]:
array2.shape

(2, 3)

In [27]:
for x in range(0, 2):
    for y in range(0, 3):
        print(array2[x][y])

1.0
2.0
3.3
4.0
5.0
6.5


In [31]:
array1

array([1, 2, 3, 4, 5])

In [28]:
array1.shape

(5,)

In [32]:
array2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
#2 partitions with 3 elements in each
#2 rows and 3 columns
array2.shape

(2, 3)

In [33]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
#2 partitions with 3 rows and 3 columns in each

array3.shape

(2, 3, 3)

In [34]:
array1.dtype

dtype('int32')

In [35]:
array2.dtype

dtype('float64')

In [36]:
array3.dtype

dtype('int32')

In [37]:
array4.dtype

dtype('int32')

In [38]:
array1.dtype,array4.dtype

(dtype('int32'), dtype('int32'))

In [39]:
array5=np.array([1,2,3,4,5],dtype='S')

In [40]:
array5

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [42]:
#Change data type from float to integer by using 'i' as parameter value:
array2conv=array2.astype('i')
array2conv

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [43]:
array2float=array2conv.astype('f')
array2float

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [44]:
numone=np.ones((2,2))
numone

array([[1., 1.],
       [1., 1.]])

In [45]:
numzero=np.zeros((2,3))
numzero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

np.random.randint(low, high=None, size=None, dtype=int)
low: int or array-like of ints: Lowest integers are drawn from the random values.
high: int or array-like of ints, optional: Larger or highest integers are drawn from the random values.
size: int or tuple of ints, optional: The shape of the array you want to create.
dtype: dtype, optional The type of the output you want.


In [47]:
# create a 1-D array
a = np.random.randint(low = 1, size = 5)
a

array([0, 0, 0, 0, 0])

In [48]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[3, 1, 2],
       [1, 4, 4]])

In [50]:
array1

array([1, 2, 3, 4, 5])

In [52]:
array4

array([12, 13, 14])

In [49]:
#concatenate two or more arrays at once
np.concatenate([array1,array4])

array([ 1,  2,  3,  4,  5, 12, 13, 14])

In [53]:
np.concatenate([array2,array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [57]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [70]:
#function returns a copy of the array collapsed into one dimension.
flatarr=array3.flatten()
flatarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [72]:
np.reshape(flatarr[:4],(2,2))

array([[1, 2],
       [3, 4]])

In [73]:
#create an identity matrix
#used to create a 2D array with ones on the diagonal and zeros elsewhere
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
#create a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(array2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [79]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [80]:
np.info(np.ndarray)

 ndarray()

ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
of